config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  root 'proponents#index'
  resources :proponents
  post '/proponents/calculate_inss_discount', to: 'proponents#calculate_inss_discount'
  get 'reports/employees_report'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/proponent.rb
class Proponent < ApplicationRecord
  MAX_SALARY = 6101.06

  SALARY_RANGES = {
    'Até R$ 1.045,00' => 0..1045.00,
    'De R$ 1.045,01 a R$ 2.089,60' => 1045.01..2089.60,
    'De R$ 2.089,61 até R$ 3.134,40' => 2089.61..3134.40,
    'De R$ 3.134,41 até R$ 6.101,06' => 3134.41..MAX_SALARY
  }

  validates :name, :cpf, :birth_date, :street, :number, :neighborhood, :city,
            :state, :zip_code, :personal_phone, :reference_phone, :salary, presence: true
  validates :salary, numericality: { less_than_or_equal_to: MAX_SALARY }
  validate :cpf_must_be_valid

  def cpf_must_be_valid
    errors.add(:cpf, 'não é válido') unless CPF.valid?(cpf)
  end

  def self.i18n_scope
    :activerecord
  end

  def self.salary_range_label(salary)
    SALARY_RANGES.detect { |label, range| range.include?(salary) }&.first
  end

  def self.grouped_by_salary_range
    ranges_count = Hash.new(0)
    all.each do |proponent|
      range_label = salary_range_label(proponent.salary)
      ranges_count[range_label] += 1 if range_label
    end
    ranges_count
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/proponents_controller.rb
class ProponentsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_proponent, only: [ :show, :edit, :update, :destroy ]

  def index
    @proponents = Proponent.page_kaminari(params[:page]).order(created_at: :desc)
  end

  def show
  end

  def new
    @proponent = Proponent.new
  end

  def create
    @proponent = Proponent.new(proponent_params)

    if @proponent.save
      flash[:notice] = 'Proponente foi criado com sucesso'
      redirect_to @proponent
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @proponent.update(proponent_params)
      flash[:notice] = 'Proponente foi atualizado com sucesso'
      redirect_to @proponent
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @proponent.destroy

    redirect_to proponents_path
  end

  def calculate_inss_discount
    gross_salary = params[:salary].to_f
    service = InssCalculationService.new(gross_salary)
    result = service.call

    render json: { discount: result[:discount] }
  end

  private

  def set_proponent
    @proponent = Proponent.find(params[:id])
  end

  def proponent_params
    params.require(:proponent).permit(:name, :cpf, :birth_date, :street, :number, :neighborhood, :city, :state, :zip_code, :personal_phone, :reference_phone, :salary)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def employees_report
    @salary_ranges = Proponent.grouped_by_salary_range
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proponents_helper.rb
module ProponentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Desconto Inss" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/chart.js@3.7.0/dist/chart.min.js' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <!-- Brand -->
        <a class="navbar-brand" href="/">Desconto INSS</a>

        <!-- Navbar toggle button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Relatório de Funcionários", reports_employees_report_path, class: "nav-link" %>
            </li>
          </ul>

          <!-- Right-aligned items -->
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/proponents/_form.html.erb
    <div class="col-md-8">
      <%= form_with(model: proponent, local: true, data: {turbo: false} ) do |form| %>
        
        <div class="mb-3">
          <%= form.label :name %>
          <%= form.text_field :name, id: 'name', class: 'form-control' %>
          <% if proponent.errors.has_key?(:name) %>
            <p class="text-danger mt-1"><%= proponent.errors[:name].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :cpf %>
          <%= form.text_field :cpf, id: 'cpf', class: 'form-control' %>
          <% if proponent.errors.has_key?(:cpf) %>
            <p class="text-danger mt-1"><%= proponent.errors[:cpf].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :birth_date %>
          <%= form.date_field :birth_date, id: 'birth_date', class: 'form-control' %>
          <% if proponent.errors.has_key?(:birth_date) %>
            <p class="text-danger mt-1"><%= proponent.errors[:birth_date].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :street %>
          <%= form.text_field :street, id: 'street', class: 'form-control' %>
          <% if proponent.errors.has_key?(:street) %>
            <p class="text-danger mt-1"><%= proponent.errors[:street].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :number %>
          <%= form.text_field :number, id: 'number', class: 'form-control' %>
          <% if proponent.errors.has_key?(:number) %>
            <p class="text-danger mt-1"><%= proponent.errors[:number].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :neighborhood %>
          <%= form.text_field :neighborhood, id: 'neighborhood', class: 'form-control' %>
          <% if proponent.errors.has_key?(:neighborhood) %>
            <p class="text-danger mt-1"><%= proponent.errors[:neighborhood].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :city %>
          <%= form.text_field :city, id: 'city', class: 'form-control' %>
          <% if proponent.errors.has_key?(:city) %>
            <p class="text-danger mt-1"><%= proponent.errors[:city].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :state %>
          <%= form.text_field :state, id: 'state', class: 'form-control' %>
          <% if proponent.errors.has_key?(:state) %>
            <p class="text-danger mt-1"><%= proponent.errors[:state].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :zip_code %>
          <%= form.text_field :zip_code, id: 'zip_code', class: 'form-control' %>
          <% if proponent.errors.has_key?(:zip_code) %>
            <p class="text-danger mt-1"><%= proponent.errors[:zip_code].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :personal_phone %>
          <%= form.text_field :personal_phone, id: 'personal_phone', class: 'form-control' %>
          <% if proponent.errors.has_key?(:personal_phone) %>
            <p class="text-danger mt-1"><%= proponent.errors[:personal_phone].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :reference_phone %>
          <%= form.text_field :reference_phone, id: 'reference_phone', class: 'form-control' %>
          <% if proponent.errors.has_key?(:reference_phone) %>
            <p class="text-danger mt-1"><%= proponent.errors[:reference_phone].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :salary %>
          <%= form.text_field :salary, id: 'salary', class: 'form-control' %>
          <% if proponent.errors.has_key?(:salary) %>
            <p class="text-danger mt-1"><%= proponent.errors[:salary].first %></p>
          <% end %>
        </div>


        <div class="mb-3">
          <%= form.label :inss_discount %>
          <%= form.text_field :inss_discount, id: 'inss_discount', class: 'form-control' %>
          <% if proponent.errors.has_key?(:inss_discount) %>
            <p class="text-danger mt-1"><%= proponent.errors[:inss_discount].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.submit "Salvar", class: 'btn btn-primary' %>
          <%= link_to 'Voltar', proponents_path, class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>

app/views/proponents/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Edição Proponente</h1>
    </div>
    <div class="col-md-8">
      <%= render 'form', proponent: @proponent %>
    </div>
  </div>
</div>

app/views/proponents/index.html.erb
<!-- app/views/proponents/index.html.erb -->

<div class="container">
  <h1 class="my-4">Lista de Proponents</h1>
  
  <%= link_to 'Novo Proponente', new_proponent_path, class: 'btn btn-primary' %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>CPF</th>
        <th>Data de Nascimento</th>
        <th>Endereço</th>
        <th>Telefones</th>
        <th>Salário</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @proponents.each do |proponent| %>
        <tr>
          <td><%= proponent.name %></td>
          <td><%= proponent.cpf %></td>
          <td><%= proponent.birth_date.strftime("%d/%m/%Y") %></td>
          <td><%= "#{proponent.street}, #{proponent.number} - #{proponent.neighborhood}, #{proponent.city} - #{proponent.state}, CEP: #{proponent.zip_code}" %></td>
          <td>
            <strong>Pessoal:</strong> <%= proponent.personal_phone %><br>
            <strong>Referência:</strong> <%= proponent.reference_phone %>
          </td>
          <td>R$ <%= number_to_currency(proponent.salary) %></td>
          <td>
            <%= link_to 'Ver', proponent %>
            <%= link_to 'Editar', edit_proponent_path(proponent) %>
            <%= link_to "Remover", proponent_path(proponent), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Tem certeza?"
                  } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="pagination">
    <%= paginate @proponents, theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center",
    nav_class: "d-inline-block" %>
  </div>
</div>

app/views/proponents/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Novo Proponente</h1>
    </div>
    <div class="col-md-8">
      <%= render 'form', proponent: @proponent %>
    </div>
  </div>
</div>

app/views/proponents/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= flash[:notice] %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <h1>Detalhes do Proponente</h1>

      <div class="card mb-3">
        <div class="card-body">
          <p><strong>Nome:</strong> <%= @proponent.name %></p>
          <p><strong>CPF:</strong> <%= @proponent.cpf %></p>
          <p><strong>Data de Nascimento:</strong> <%= @proponent.birth_date %></p>
          <p><strong>Endereço:</strong> <%= @proponent.street %>, <%= @proponent.number %> - <%= @proponent.neighborhood %></p>
          <p><strong>Cidade:</strong> <%= @proponent.city %> - <%= @proponent.state %>, <%= @proponent.zip_code %></p>
          <p><strong>Telefone Pessoal:</strong> <%= @proponent.personal_phone %></p>
          <p><strong>Telefone de Referência:</strong> <%= @proponent.reference_phone %></p>
          <p><strong>Salário:</strong> <%= number_to_currency(@proponent.salary, unit: 'R$', precision: 2) %></p>
        </div>
      </div>

      <%= link_to 'Editar', edit_proponent_path(@proponent), class: 'btn btn-primary me-2' %>
      <%= link_to 'Voltar', proponents_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/reports/employees_report.html.erb
<h1>Relatório dos Funcionários</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Faixa Salarial</th>
      <th>Número de Funcionários</th>
    </tr>
  </thead>
  <tbody>
    <% @salary_ranges.each do |range, count| %>
      <tr>
        <td><%= range %></td>
        <td><%= count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<canvas id="salaryChart" width="400" height="400"></canvas>

<script>
  document.addEventListener('turbo:load', () => {
    const ctx = document.getElementById('salaryChart').getContext('2d');
    const myChart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: <%= @salary_ranges.keys.to_json.html_safe %>,
        datasets: [{
          label: 'Número de Funcionários por Faixa Salarial',
          data: <%= @salary_ranges.values.to_json.html_safe %>,
          backgroundColor: [
            'rgba(255, 99, 132, 0.2)',
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
          ],
          borderColor: [
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
          ],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  });
</script>